---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      network:
        - ["private_network", {ip: "10.10.12.5"}]

suites:
  - name: default
    run_list:
      - recipe[preview::default]
    attributes:
